apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: pr-{{ .Values.prNumber }}.{{ .Values.minikubeIp }}.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
