apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pr-{{ .Values.prNumber }}-ing
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: pr-{{ .Values.prNumber }}.{{ .Values.minikubeIp }}.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pr-{{ .Values.prNumber }}-svc
                port:
                  number: 80
