pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'sharmachandan487'
        DOCKER_IMAGE   = "${DOCKERHUB_USER}/pr-preview-app"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Push Image') {
          steps {
              script {
                  def prId = env.CHANGE_ID ?: "local"
                  def image = "${env.DOCKERHUB_USER}/pr-preview-app:pr-${prId}"

                  withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', 
                                                    usernameVariable: 'DOCKERHUB_USER', 
                                                    passwordVariable: 'DOCKERHUB_PASS')]) {
                      bat """
                          docker --version
                          echo Logging in to DockerHub...
                          echo %DOCKERHUB_PASS% | docker login -u %DOCKERHUB_USER% --password-stdin
                          echo Building image: ${image}
                          docker build -t ${image} app
                          echo Pushing image: ${image}
                          docker push ${image}
                      """
                  }
              }
          }
        }

        stage('Deploy with Helm') {
          steps {
              script {
                  def prId = env.CHANGE_ID ?: "local"
                  def image = "${env.DOCKERHUB_USER}/pr-preview-app:pr-${prId}"

                  powershell """
                      $pr = "$prId"
                      $minikubeIp = (minikube ip)

                      echo "Creating namespace pr-$pr if not exists..."
                      kubectl create namespace pr-$pr --dry-run=client -o yaml | kubectl apply -f -

                      echo "Deploying with Helm..."
                      helm upgrade --install pr-$pr ./helm-chart `
                          --namespace pr-$pr `
                          --set image.repository=${env.DOCKERHUB_USER}/pr-preview-app `
                          --set image.tag=pr-$pr `
                          --set prNumber=$pr `
                          --set minikubeIp=$minikubeIp
                  """
              }
          }
        }

        stage('Verify Deployment') {
            steps {
                powershell """
                    $pr = $env:CHANGE_ID
                    kubectl get pods -n pr-$pr
                    kubectl get ingress -n pr-$pr
                """
            }
        }
    }

    post {
        success {
            echo "PR Preview deployed successfully! 🎉"
            echo "Visit: http://pr-${env.CHANGE_ID}.`minikube ip`.nip.io/"
        }
        failure {
            echo "Deployment failed. Check logs."
        }
    }
}
