name: PR Cleanup (trigger Jenkins destroy)

on:
  pull_request:
    types: [closed]

jobs:
  destroy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins destroy
        if: ${{ secrets.JENKINS_URL && secrets.JENKINS_USER && secrets.JENKINS_TOKEN && secrets.JENKINS_JOB }}
        run: |
          PR=${{ github.event.pull_request.number }}
          curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"             "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB }}/buildWithParameters?PR_NUMBER=${PR}&ACTION=destroy"
